// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFemAqdUvHrHjDENOLFx9WxTjypkkN2po',
    appId: '1:23265461996:web:beb49257aac9da5e6a47c9',
    messagingSenderId: '23265461996',
    projectId: 'social-app-3fbea',
    authDomain: 'social-app-3fbea.firebaseapp.com',
    storageBucket: 'social-app-3fbea.appspot.com',
    measurementId: 'G-VPQ3BKKGKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALdsr3FbFCcb5EJXbVVjBQurP8F1j8Rpw',
    appId: '1:23265461996:android:ac7d061754ce76576a47c9',
    messagingSenderId: '23265461996',
    projectId: 'social-app-3fbea',
    storageBucket: 'social-app-3fbea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcvt0UKbiHZuprWshQfczFPhjGtpmwVk',
    appId: '1:23265461996:ios:5c754881805db6c66a47c9',
    messagingSenderId: '23265461996',
    projectId: 'social-app-3fbea',
    storageBucket: 'social-app-3fbea.appspot.com',
    androidClientId: '23265461996-uenft1bikv257r2dthvft982f2s55ngk.apps.googleusercontent.com',
    iosClientId: '23265461996-t0lgn3qg63mul7k0gq29a06gvkf292nd.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcvt0UKbiHZuprWshQfczFPhjGtpmwVk',
    appId: '1:23265461996:ios:5c754881805db6c66a47c9',
    messagingSenderId: '23265461996',
    projectId: 'social-app-3fbea',
    storageBucket: 'social-app-3fbea.appspot.com',
    androidClientId: '23265461996-uenft1bikv257r2dthvft982f2s55ngk.apps.googleusercontent.com',
    iosClientId: '23265461996-t0lgn3qg63mul7k0gq29a06gvkf292nd.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGbsp7ERoF60cTgATbK84Qv1aMqkmm0NY',
    appId: '1:23265461996:web:17966b9b51e939126a47c9',
    messagingSenderId: '23265461996',
    projectId: 'social-app-3fbea',
    authDomain: 'social-app-3fbea.firebaseapp.com',
    storageBucket: 'social-app-3fbea.appspot.com',
    measurementId: 'G-VWZTYNLLBN',
  );
}
