// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_stg.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrsIt4S9el7QsJynhGqkr498EcnpfYazU',
    appId: '1:846526377811:web:9dc1e35f2b68a08eff3ba6',
    messagingSenderId: '846526377811',
    projectId: 'social-app-stg-af02f',
    authDomain: 'social-app-stg-af02f.firebaseapp.com',
    storageBucket: 'social-app-stg-af02f.firebasestorage.app',
    measurementId: 'G-Z3CM7GLM9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTftS7BWNRKRQg8BzlME9_6xaWIVuaaD0',
    appId: '1:846526377811:android:56aeeed72cdfb871ff3ba6',
    messagingSenderId: '846526377811',
    projectId: 'social-app-stg-af02f',
    storageBucket: 'social-app-stg-af02f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf-YqP1LHjIYH1M5sKTTTI6mqvymp7cXc',
    appId: '1:846526377811:ios:5491d8c832b34ae6ff3ba6',
    messagingSenderId: '846526377811',
    projectId: 'social-app-stg-af02f',
    storageBucket: 'social-app-stg-af02f.firebasestorage.app',
    iosClientId: '846526377811-iuoaious4g9jn7vrmbutestfuvpi79ep.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf-YqP1LHjIYH1M5sKTTTI6mqvymp7cXc',
    appId: '1:846526377811:ios:12722f57db88c454ff3ba6',
    messagingSenderId: '846526377811',
    projectId: 'social-app-stg-af02f',
    storageBucket: 'social-app-stg-af02f.firebasestorage.app',
    iosClientId: '846526377811-2i9c5g9q1ac8cogguj7glqtvh9v972jn.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrsIt4S9el7QsJynhGqkr498EcnpfYazU',
    appId: '1:846526377811:web:beb856e0d91a823dff3ba6',
    messagingSenderId: '846526377811',
    projectId: 'social-app-stg-af02f',
    authDomain: 'social-app-stg-af02f.firebaseapp.com',
    storageBucket: 'social-app-stg-af02f.firebasestorage.app',
    measurementId: 'G-BNR2ZS6NZL',
  );
}
