// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN7tQM33kXaTwQBpOuYURrWja-snqTYxE',
    appId: '1:490911373311:web:f1df73ece3c2c6ae9439ca',
    messagingSenderId: '490911373311',
    projectId: 'social-app-dev-2692e',
    authDomain: 'social-app-dev-2692e.firebaseapp.com',
    storageBucket: 'social-app-dev-2692e.firebasestorage.app',
    measurementId: 'G-YGHTFYNBZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjDUXJOWoqNdpqZoaHdbpNmBK6pf4jYcQ',
    appId: '1:490911373311:android:772d5ac47b05f67f9439ca',
    messagingSenderId: '490911373311',
    projectId: 'social-app-dev-2692e',
    storageBucket: 'social-app-dev-2692e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5uf9A7ujtv5_cCchIb1Bir0y0glBy04I',
    appId: '1:490911373311:ios:3927778a5ac24b839439ca',
    messagingSenderId: '490911373311',
    projectId: 'social-app-dev-2692e',
    storageBucket: 'social-app-dev-2692e.firebasestorage.app',
    iosClientId: '490911373311-1e02l3ilkpkjuf2fsstbgiaao7i4oo06.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5uf9A7ujtv5_cCchIb1Bir0y0glBy04I',
    appId: '1:490911373311:ios:a7c57b3a888fc7bb9439ca',
    messagingSenderId: '490911373311',
    projectId: 'social-app-dev-2692e',
    storageBucket: 'social-app-dev-2692e.firebasestorage.app',
    iosClientId: '490911373311-3eesu926snk8ulp1lahuog375ilf4qhm.apps.googleusercontent.com',
    iosBundleId: 'com.derodian.socialApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN7tQM33kXaTwQBpOuYURrWja-snqTYxE',
    appId: '1:490911373311:web:94e9df2d5216ed2a9439ca',
    messagingSenderId: '490911373311',
    projectId: 'social-app-dev-2692e',
    authDomain: 'social-app-dev-2692e.firebaseapp.com',
    storageBucket: 'social-app-dev-2692e.firebasestorage.app',
    measurementId: 'G-L6L5P8PQ69',
  );
}
